// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://likgblxtyeopyzjcxufo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxpa2dibHh0eWVvcHl6amN4dWZvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2MjU3MDMsImV4cCI6MjA2ODIwMTcwM30.TurKpCuZQe7xRN7zovM0j9K7HueNCa7isygf1_udIpI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});